### ISSUE TITLE
设备的高度和速度的问题

### ISSUE THREAD

**Issue by hunantangyuyang** [besovideo/Android-BVCU-SDK-Demo#1]
可以把设备的速度和高度这两个字段也返回一下吗？

**Comment by xuwei9** [comment]
参见开发手册中看下相关属性，com.smarteye.adapter.BVCU_PUCFG_GPSData

**Comment by hunantangyuyang** [comment]
现在有一个这样的业务场景：进入主界面地图直接查询在线的设备，然后把在线的设备显示到地图上，而bvcu_puChannelInfo的经纬度为0不能定位到正确的坐标上，所以上次已经提了这个问题。这份新的代码提供了主动查询设备坐标信息的方法，但是并不特别适用于我们这个业务场景，当加载完在线的设备列表后，再逐个请求设备定位信息，每一个设备需大概2秒才能返回GPS信息

**Comment by hunantangyuyang** [comment]
这样在交互上就让使用者感觉很笨重，贵司能不能在查询设备列表的时候，把最新的经纬度传到回调里返回的BVCU_PUChannelInfo实体中？

**Comment by jinbo1996** [comment]
查询设备列表返回的BVCU_PUChannelInfo结构体中的经纬度是登录时传入的坐标信息，登录时设备可能尚未获取到当定位信息，所以可能为空。上次DEMO中新增的请求设备定位命令是打开设备GPS通道，会一直返回该设备的实时定位信息，所以会有些延迟。请尝试调用这条查询命令：BVCU_SUBMETHOD_PU_GPSDATA，返回设备当前最新定位，具体使用请参考开发手册。

**Comment by hunantangyuyang** [comment]
我发送了命令，回调中的OnCmdEvent函数却没有返回，是不是我代码缺少了参数？
BVCU_Command command = new BVCU_Command();
        command.iMethod = BVCU_Method.BVCU_METHOD_QUERY;
        command.iSubMethod =  BVCU_SubMethod.BVCU_SUBMETHOD_PU_GPSDATA;
        command.szTargetID = deviceID;
        command.iTargetIndex = 0;
        int token = BVCU.getSDK().sendCmd(command);

**Comment by jinbo1996** [comment]
你查询的目标设备上运行的是什么程序，mpu?mcp?

**Comment by hunantangyuyang** [comment]
> 你查询的目标设备上运行的是什么程序，mpu?mcp?

MPU

**Comment by jinbo1996** [comment]
什么版本

**Comment by hunantangyuyang** [comment]
版本编号是1850，版本名称20190315

**Comment by jinbo1996** [comment]
好的，我这边测测看看

**Comment by hunantangyuyang** [comment]
> 查询设备列表返回的BVCU_PUChannelInfo结构体中的经纬度是登录时传入的坐标信息，登录时设备可能尚未获取到当前定位信息，所以可能为空。上次DEMO中新增的请求设备定位信息命令是打开设备GPS通道，会一直返回该设备的实时定位信息，所以会有些延迟。请尝试调用这条查询命令：BVCU_SUBMETHOD_PU_GPSDATA，返回设备当前最新定位，具体使用请参考开发手册。

如果BVCU_PUChannelInfo这个实体可以在设备上线后，间歇性更新GPS信息到这个实体就好了阿，可以做到吗？

**Comment by jinbo1996** [comment]
目前不支持这种方式，开发者可以使用BVCU_SUBMETHOD_PU_GPSDATA查询命令来实现，请用以下的jar包和so替换demo中的库，重新调用BVCU_SUBMETHOD_PU_GPSDATA查询命令

**Comment by jinbo1996** [comment]
目前不支持这种方式，开发者可以使用BVCU_SUBMETHOD_PU_GPSDATA查询命令来实现，请用以下的jar包和so替换demo中的库，重新调用BVCU_SUBMETHOD_PU_GPSDATA查询命令

**Comment by jinbo1996** [comment]
[newLib.zip](https://github.com/besovideo/Android-BVCU-SDK-Demo/files/4309848/newLib.zip)
