### ISSUE TITLE
关于绕过MCU功能认证的问题

### ISSUE THREAD

**Issue by hunantangyuyang** [besovideo/Android-BVCU-SDK-Demo#2]
一、我司开发的APP所用到的功能包括：1.登录  2.视频监控预览 3.语音对讲 4.查询设备列表 5.查询文件列表  现在我发现第4点和第5点都需要经过认证才能使用，我采纳了汪经理的意见不勾选UA，但是并没有效果。
二、我在论坛发帖有相关人员回复我：手机上安装我们标准的MAP APK做好认证可以通用于这份代码的认证。
基于帖子回答“无UA不认证的”办法我产生了以下疑问：1.我在工程BVCU-SDK-Demo-master的代码中如何像标准MAP APK那样“连续点击空白处7次”那样获取认证码？  2.这个认证码参数我设置在哪里？设到登录方法中的BVCU_SessionParam.szClientID吗。
三、如果“无UA不认证”这个办法可以使用如我第一条描述问题中的第4、第5点功能的话，可以完善相关代码吗，或者提供相关代码片段让我自己完善

**Comment by jinbo1996** [comment]
![TIM图片20200407123610](https://user-images.githubusercontent.com/55678358/78631146-1c343100-78ce-11ea-8b70-96a78d785bbc.png)
![TIM图片20200407124433](https://user-images.githubusercontent.com/55678358/78631153-1e968b00-78ce-11ea-805b-64288291f1dc.png)
卸载重装再测试

**Comment by blackfire-obj** [comment]
按理说，只要是CU功能，就不需要认证。
你这个检索文件，是去检索另外一个设备里面的录像文件吧？如果是这样，那就应该是CU功能，
这个不应该走认证

**Comment by hunantangyuyang** [comment]
非常感谢，按照上诉的办法修改代码之后，经过初步测试发现没有问题。这个问题已解决了，辛苦了
