### ISSUE TITLE
关于音频编码格式的问题

### ISSUE THREAD

**Issue by zhanghongqiang** [besovideo/Android-BVCU-SDK-Demo#3]
SDK内部是否支持mp3编码？

**Comment by xuwei9** [comment]
不支持

**Comment by blackfire-obj** [comment]
@xuwei9  他们是我们铁杆兄弟伙伴，他们有我们全套的MCP SDK，他们可否自己添加此功能，我们配合做一些修改？包括平台侧的？

**Comment by xuwei9** [comment]
> @xuwei9 他们是我们铁杆兄弟伙伴，他们有我们全套的MCP SDK，他们可否自己添加此功能，我们配合做一些修改？包括平台侧的？

编码格式是平台和设备的通信协议定的，SDK客户没法自己修改支持，需要添加的话要商务转给陈经理

**Comment by xuwei9** [comment]
> SDK内部是否支持mp3编码？

如果是需要MP3录音文件或者MP4录像文件支持MP3音频编码，可以使用ffmpeg库来实现，http://ffmpeg.org/,网上的demo参考https://download.csdn.net/download/hiwubihe/10569791

**Comment by zhanghongqiang** [comment]
好的，非常感谢
